export { Layout as PageLayout } from "./Layout"
export { Home as PageHome } from "./Home"
export { Cadastrar as PageCadastrar } from "./Cadastrar"
export { Login as PageLogin } from "./Login"
export {Galeria as PageDois} from "./Galeria"
export { Adm as PageAdm } from "./Adm"